services:
  - type: web
    name: n4f-factuurgenerator
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT n4f_flask_factuurgenerator:app
    autoDeploy: true